"role: build_output_folders":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/build_output_folders/*
          - ansible_collections/arista/avd/roles/build_output_folders/**/*

"role: cvp_configlet_upload":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/cvp_configlet_upload/*
          - ansible_collections/arista/avd/roles/cvp_configlet_upload/**/*

"role: eos_cli_config_gen":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_cli_config_gen/*
          - ansible_collections/arista/avd/roles/eos_cli_config_gen/**/*

"role: eos_config_deploy_cvp":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_config_deploy_cvp/*
          - ansible_collections/arista/avd/roles/eos_config_deploy_cvp/**/*

"role: eos_config_deploy_eapi":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_config_deploy_eapi/*
          - ansible_collections/arista/avd/roles/eos_config_deploy_eapi/**/*

"role: eos_designs":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_designs/*
          - ansible_collections/arista/avd/roles/eos_designs/**/*

"role: eos_validate_state":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_validate_state/*
          - ansible_collections/arista/avd/roles/eos_validate_state/**/*

"role: eos_snapshot":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/eos_snapshot/*
          - ansible_collections/arista/avd/roles/eos_snapshot/**/*

"role: dhcp_provisioner":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/roles/dhcp_provisioner/*
          - ansible_collections/arista/avd/roles/dhcp_provisioner/**/*

"filter: natural_sort":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/filter/natural_sort.py

"filter: is_in_filter":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/filter/is_in_filter.py

"filter: list_compress":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/filter/list_compress.py

"filter: defined":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/filter/defined.py

"module: configlet_build_config":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/modules/configlet_build_config.py

"module: inventory_to_container":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/modules/inventory_to_container.py

"type: Python filters":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/filter/*.py

"type: Ansible roles":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/plugins/roles/**/*.yml
          - ansible_collections/arista/avd/plugins/roles/**/*.j2

"state: Documentation role Updated":
  - changed-files:
      - any-glob-to-any-file:
          - 'ansible_collections/arista/avd/roles/**/*.md'

"type: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - contributing.md
          - ansible_collections/arista/avd/*.md
          - ansible_collections/arista/avd/docs/*
          - ansible_collections/arista/avd/docs/**/*

"type: code quality":
  - changed-files:
      - any-glob-to-any-file:
          - .github/labeler.yml
          - .github/*
          - .github/**/*
          - development/docker-compose.yml
          - development/Makefile

"type: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - development/requirements-dev.txt
          - development/requirements.txt
          - ansible_collections/arista/avd/docs/requirements.txt

"state: CI Updated":
  - changed-files:
      - any-glob-to-any-file:
          - ansible_collections/arista/avd/molecule/*
          - ansible_collections/arista/avd/molecule/**/*
