---
name: Build dev container

on:
  push:
    branches:
      - devel
    paths:
      - containers/dev/**
      - .github/workflows/container_build_template.yml
      - .github/workflows/container_build_dev.yml
  workflow_dispatch:
    branches:
      - devel

jobs:
  build_dev_container:
    if: github.repository == 'aristanetworks/avd'
    uses: ./.github/workflows/container_build_template.yml
    strategy:
      matrix:
        container_name: [dev]
        python_version: ["3.10", "3.11", "3.12"]
        include:
          - python_version: "3.11"
            container_tags: latest
    with:
      container_name: ${{ matrix.container_name }}
      python_version: ${{ matrix.python_version }}
      container_tags: ${{ matrix.container_tags }}
