---
name: Build universal container

on:
  push:
    branches:
      - devel
    paths:
      - containers/universal/**
      - .github/workflows/container_build_template.yml
      - .github/workflows/container_build_universal.yml
      - ansible_collections/arista/avd/**
  workflow_dispatch:
    branches:
      - devel
  release:
    types: [published]

jobs:
  build_universal_container:
    if: github.repository == 'aristanetworks/avd'
    uses: ./.github/workflows/container_build_template.yml
    strategy:
      matrix:
        container_name: [universal]
        python_version: ["3.10", "3.11", "3.12"]
        include:
          - python_version: "3.11"
            container_tags: latest
    with:
      container_name: ${{ matrix.container_name }}
      python_version: ${{ matrix.python_version }}
      container_tags: ${{ matrix.container_tags }}
